# Generated by Django 4.2.5 on 2023-09-04 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.SlugField(max_length=200)),
                ('place', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='places.places')),
            ],
        ),
    ]
